### ISSUE TITLE
Capabilities para Usuário Editor

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/techcd-theme#37]
@matheusgimenez aplica isso nos usuários "Editor". Precisamos que ele tenha capacidade de ver os menus /Aparência/Menus, /Aparência/Widgets e /Aparência/Opções do Tema.

**Comment by LuwkasLima** [comment]
fui fazer uma modificacao como Editor no Aparencias e apareceu isso:

![image](https://cloud.githubusercontent.com/assets/5949986/7813499/54c2fda2-0381-11e5-89c2-0ff6c3223dbc.png)

Me parece que o usuário Editor ainda não possui todos os privilégios para modificação.
